app:
  image:
    repository: "onecx-apps/onecx-chat-svc"
    tag: 999-SNAPSHOT
  db:
    enabled: true
  operator:
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-tn:read ]